### ISSUE TITLE
ReferrersManager causing index error

### ISSUE THREAD

**Issue by Micsi** [sgiehl/piwik-plugin-ReferrersManager#12]
Hi,

in Piwik 3.0.4, we are getting the following error when accessing the eMail reports config page with active reports:

WARNING: /srv/www/laborumgebung/statistik/htdocs/plugins/ScheduledReports/ScheduledReports.php(197): Notice - Undefined index: category - Piwik 3.0.4 - Please report this message in the Piwik forums: http://forum.piwik.org (please do a search first as it might have been reported already)

If you search the forum, you will find that some 3rd party plugins are not fully compatible to Piwik 3.x and causing this. In our installation I was able to identify ReferrerManager as causing the problem.

Regards
Jochen

**Comment by sgiehl** [comment]
ReferrersManager plugin should be fully compatible with Piwik 3. 
It's almost impossible that ReferrersManager plugin can cause this error. 
It happens when a report provided by a plugin has no category set. As ReferrersManager plugin does not provide any kind of reports it can't cause this error. 
Do you have any other third party plugins installed?

**Comment by Micsi** [comment]
Hallo Stefan,

yes, we have other 3rd party plugins installed:

AOM
CustomOptOut
FlagCounter

The error goes away, when I disable ReferresManager

Regards
Jochen

**Comment by Findus23** [comment]
Recently I read a report of someone also getting errors with AOM:

https://forum.piwik.org/t/piwik-in-jtl-shop-integrieren/24431/19

In addition it should be the only plugin from your list that uses ScheduledReports.

**Comment by Micsi** [comment]
OH SORRY. Another reload brings back the problem. You are right, it seems to be there’s another source of the problem.

Sorry for the hassle.

Regards
Jochen
