### ISSUE TITLE
news.google.com is added as a website rather than a channel

### ISSUE THREAD

**Issue by jmumby** [sgiehl/piwik-plugin-ReferrersManager#25]
News.google.com is tracked as a website rather than search engines in the referrers report. 

![image](https://user-images.githubusercontent.com/4339071/98600357-4bb68a80-2342-11eb-866b-9385b7f11251.png)

How can we configure this source to appear in search engines rather than websites?

**Comment by Findus23** [comment]
Hi,

news.google.com is ins the search engines list, but it requires that the referrer contains a `?q=` query string. I assume that google news only sends the domain as a referrer and therefore it doesn't match
 https://github.com/matomo-org/searchengine-and-social-list/blob/9d2cfff43c899f2aed0f94df7496537f830b3940/SearchEngines.yml#L1078-L1084

I guess something like this needs to be added:
https://github.com/matomo-org/searchengine-and-social-list#hiddenkeyword

https://github.com/matomo-org/searchengine-and-social-list/blob/9d2cfff43c899f2aed0f94df7496537f830b3940/SearchEngines.yml#L895

**Comment by mattab** [comment]
Hi @sgiehl, would it be possible to implement this change in the list?

**Comment by sgiehl** [comment]
This will be automatically fixed with https://github.com/matomo-org/matomo/pull/16747
