### ISSUE TITLE
Search engines without URL parameters are popping up and are not recognized

### ISSUE THREAD

**Issue by peterbo** [sgiehl/piwik-plugin-ReferrersManager#27]
More and more (smaller) search engines are omitting URL parameters. These search engines are therefore not recognized anymore as a Search Engine referrer. The Referrers manager accepts Input without Parameters (Hostname only), but these Hostnames never geht matched to the corresponding engine:

![startpage](https://user-images.githubusercontent.com/1018973/105176094-0cb46a80-5b25-11eb-8c2a-0ddede986c66.JPG)

That applies for example for startpage.com, metager.de (configurable).

**Comment by sgiehl** [comment]
That should actually already be handled in Matomo with https://github.com/matomo-org/matomo/pull/16747

**Comment by peterbo** [comment]
This instance is on version 4.1.0. The example is startpage.com:

Search result click on URL: https://startpage.com/sp/search
-> Referrer is recognized as website:
![startpage1](https://user-images.githubusercontent.com/1018973/105179206-50a96e80-5b29-11eb-837a-b058da38c0f4.JPG)

That's what the Matomo tracking code records as referrer after entering the landingpage:
![startpage2](https://user-images.githubusercontent.com/1018973/105179464-abdb6100-5b29-11eb-94d4-6f434ab038ed.JPG)

Similar things happen to (certain settings I presume) others:
![baidu](https://user-images.githubusercontent.com/1018973/105180236-9450a800-5b2a-11eb-96ed-5f9e060942e9.JPG)
![metager](https://user-images.githubusercontent.com/1018973/105180239-94e93e80-5b2a-11eb-95c6-c2d2c0eda435.JPG)

**Comment by Findus23** [comment]
Strange. In addition, even without https://github.com/matomo-org/matomo/pull/16747 this fix should make sure that Startpage is also detected correctly in Matomo 3:

https://github.com/matomo-org/searchengine-and-social-list/pull/75 and https://github.com/matomo-org/searchengine-and-social-list/pull/78

**Comment by peterbo** [comment]
@Findus23 I found that in another instance, which is running 3.13.5:
![3135-metager](https://user-images.githubusercontent.com/1018973/105180788-48eac980-5b2b-11eb-80f8-76827339d56a.JPG)

However, in 3.13.5, there are no incorrectly recognized "StartPage" referrers. But maybe the Website is too small to get a "critical" amount of all possibilities.

**Comment by peterbo** [comment]
I found the reason for that (since in one instance and the Matomo Demo, it worked), but I can't say, what the underlying issue causes this.

- I compared the Search engine definitions returned by "getDefinitions()" in Referrers/SearchEngine.php which was different in both 4.x instances
- composer / vendor package matomo/searchengine-and-social-list however, were the same in both 4.x instances
- clearing the cache recreated the same (old) SE definition list in the instance, that didn't work
- searching through the code, I found that the SearchEngineDefinitions are fetched from the matomo_options table (if no cache hit), before pulling them from the yml file.
- I renamed the matomo_options "option_name" (SearchEngineDefinitions -> SearchEngineDefinitions_old) and recreated the cache
- The instance that didn't work before, now recognizes StartPage correctly (and returns correct SearchEngineDefinitions)

Could you think of any case, where the SearchEngineDefinitions in the database weren't updated? - I didn't do this specific update myself, so I don't have any further info on the update vector from 3.x to 4.x.

**Comment by peterbo** [comment]
For MetaGer, the recognition doesn't work, even after the fix (the recognition fails for all instances, also Matomo demo):

![metager2](https://user-images.githubusercontent.com/1018973/105257231-a280e180-5b87-11eb-92c4-e189768960a3.JPG)
![metager3](https://user-images.githubusercontent.com/1018973/105257232-a280e180-5b87-11eb-8973-28aeed519d45.JPG)

**Comment by peterbo** [comment]
Added the hiddenkeyword (https://github.com/matomo-org/searchengine-and-social-list/issues/60) to MetaGer as well -> works.

**Comment by sgiehl** [comment]
@peterbo There is a scheduled task that should fetch the latest version from github weekly and update the definitions in the option table. Maybe that task doesn't run correctly for one of your instances?

**Comment by Findus23** [comment]
This might be related to https://github.com/matomo-org/matomo/issues/15923

Do you by chance have `enable_internet_features` disabled? But even then https://github.com/matomo-org/matomo/pull/15951 should have fixed it.

**Comment by peterbo** [comment]
Hi Lukas @Findus23, `enable_internet_features` is not changed in the config (->enabled). Scheduled tasks are not disabled / running every two hours.

Triggering manually also works:
`
root@piwik:/var/www/piwik# php console scheduled-tasks:run 'Piwik\Plugins\Referrers\Tasks.updateSearchEngines' --force
INFO [2021-01-21 11:12:33] 12027  Scheduler: executing task Piwik\Plugins\Referrers\Tasks.updateSearchEngines...
INFO [2021-01-21 11:12:34] 12027  Scheduler: finished. Time elapsed: 0.247s
Time elapsed: 0.247s

Scheduled Tasks executed
`
The instance was updated about 2 weeks ago. Perhaps the archiver ran out of memory last week, so the scheduled tasks didn't run. The log is cleared for every run unfortunately, so I can't trace it. Perhaps it was just a glitch. Thanks for your help, guys! Should I send a PR for the MetaGer adjustment or will you edit this on the next version anyway?

**Comment by sgiehl** [comment]
@peterbo Metager seems not to have a hidden keyword defined in the definition. So as of Matomo 4.1 it should automatically be detected. Not sure if we should add it nevertheless. Guess that might end up in adding it everywhere...

**Comment by peterbo** [comment]
@sgiehl - I'm not sure about this either, but as you can see in the Matomo Demo screenshots above, it is not recognized as Search engine. After adding the hidden keyword definition:
`    hiddenkeyword:
      - '/^$/'
      - '/'`
      
It works.
