### ISSUE TITLE
Allow multiple hosts for custom entry

### ISSUE THREAD

**Issue by sbrickey** [sgiehl/piwik-plugin-ReferrersManager#6]
My site has its own built-in search engine.

My site is also accessible either using the www FQDN, or through the @ hostname.

I would like them to be represented as a single "search engine", just as the built-in entries are able to do.

**Comment by sgiehl** [comment]
Sry for the late reply. That is already possible.
To have multiple hosts for the same engine, simply use the same name. But ensure to add the base entry first, otherwise backlinks might get formatted with the wrong url
